[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "google-api-python-client>=2.166.0",
    "uvicorn>=0.34.0",
    "youtube-transcript-api>=1.0.3",
]
