services:
- type: web
  name: youtube-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: YOUTUBE_API_KEY
      sync: false
    - key: API_KEY
      sync: false